import type { ZiweiScopeMode } from '@/lib/query-state';
import type { InspirationCategory } from './ResultPage.types';

export const inspirationCategories: InspirationCategory[] = [
  '全部',
  '近期',
  '事业',
  '财运',
  '婚恋',
  '子女',
  '六亲',
  '家庭',
  '人际',
  '情绪',
  '健康',
  '学业',
  '成长',
  '天赋',
];

export const commonQuestionInspirations: Array<{
  category: Exclude<InspirationCategory, '全部'>;
  question: string;
}> = [
  { category: '近期', question: '我近期最该优先推进的事情是什么？' },
  { category: '近期', question: '我最近更适合主动出击，还是先稳住节奏？' },
  { category: '近期', question: '我近期最需要回避的风险点是什么？' },
  { category: '近期', question: '如果我最近想做调整，最值得先动哪一块？' },
  { category: '近期', question: '我现在这段时间的主线课题到底是什么？' },
  { category: '近期', question: '我近期更适合守成、变动，还是试探新机会？' },
  {
    category: '事业',
    question: '我现在适合换工作，还是先留在原岗位继续积累？',
  },
  {
    category: '事业',
    question: '这次跳槽机会更值得抓住，还是先稳住现有节奏？',
  },
  {
    category: '事业',
    question: '如果我现在想转方向，更适合留在原行业深耕，还是切换赛道？',
  },
  {
    category: '事业',
    question: '我现在更适合创业、找人合作，还是先继续上班积累？',
  },
  {
    category: '事业',
    question: '如果我想自己做点事，现在更适合单干、合伙，还是先小范围试水？',
  },
  {
    category: '事业',
    question: '这条创业方向现在值得投入吗，还是更适合先观望准备？',
  },
  { category: '事业', question: '我更适合走稳定上班路线，还是尝试主动开拓发展？' },
  { category: '事业', question: '我在工作中更适合做执行、管理、专业技术，还是资源整合？' },
  { category: '事业', question: '我现在的事业卡点主要出在能力、人际还是选择方向？' },
  { category: '事业', question: '如果想换工作，我更该优先看平台、收入还是成长空间？' },
  { category: '事业', question: '我适不适合创业，还是更适合在体系内发展？' },
  { category: '事业', question: '我更适合留在熟悉领域深耕，还是切换到新方向？' },
  { category: '事业', question: '我在职场里最容易被看到的优势是什么？' },
  { category: '事业', question: '我在工作合作中更适合主导还是辅助？' },
  { category: '事业', question: '如果想提升事业发展，我最该先补哪一项能力？' },
  { category: '事业', question: '我的事业压力更多来自外部环境还是自己选择？' },
  { category: '财运', question: '我的财运更偏正财还是偏财？' },
  { category: '财运', question: '我更适合靠工资积累，还是靠副业、项目、经营来赚钱？' },
  { category: '财运', question: '我在财务上最容易踩的坑是什么？' },
  { category: '财运', question: '我更适合求稳理财，还是适度冒险争取更大收益？' },
  { category: '财运', question: '我的财富积累重点更在开源还是守财？' },
  { category: '财运', question: '我赚钱时更该依赖专业能力还是资源整合能力？' },
  { category: '财运', question: '我在金钱决策上更容易冲动还是保守？' },
  { category: '财运', question: '我是否容易出现赚得快但留不住的情况？' },
  {
    category: '财运',
    question: '我现在适合自己投、跟人合作求财，还是先守住现金流继续观望？',
  },
  {
    category: '财运',
    question: '这次投资或合作机会更像能放大的机会，还是容易带来额外风险和牵扯？',
  },
  {
    category: '财运',
    question: '如果我想靠项目、投资或合作赚钱，现在更适合主动布局还是先把风险控住？',
  },
  { category: '财运', question: '我适不适合和别人一起做生意或投资？' },
  { category: '财运', question: '如果要改善财务状态，我最该先管住哪一块？' },
  { category: '婚恋', question: '我的感情模式更容易主动、被动，还是反复拉扯？' },
  {
    category: '婚恋',
    question: '我现在更适合主动推进这段关系，还是先观察一段时间？',
  },
  {
    category: '婚恋',
    question: '这段关系现在值得继续投入，还是该慢下来重新判断？',
  },
  {
    category: '婚恋',
    question: '面对这段感情，我更该主动争取、稳定经营，还是及时止损？',
  },
  {
    category: '婚恋',
    question: '这段关系我现在该继续投入，还是该及时抽身止损？',
  },
  {
    category: '婚恋',
    question: '如果继续这段关系，我是在等结果，还是在消耗自己？',
  },
  {
    category: '婚恋',
    question: '这段感情现在更适合继续观察，还是该尽快做去留判断？',
  },
  {
    category: '婚恋',
    question: '这段旧关系现在还有没有复合空间，我更适合争取、观察还是直接放下？',
  },
  {
    category: '婚恋',
    question: '如果我还想回头看这段关系，现在是在等机会，还是在继续消耗自己？',
  },
  {
    category: '婚恋',
    question: '这段旧感情当前更像能重新连接的机会，还是该趁早收口止损？',
  },
  { category: '婚恋', question: '我适合什么类型的伴侣？' },
  { category: '婚恋', question: '我的未来对象大概是怎样的人？' },
  { category: '婚恋', question: '我更容易在哪类场景或圈层遇到未来对象？' },
  { category: '婚恋', question: '未来对象出现时，我应该重点观察哪些信号？' },
  { category: '婚恋', question: '我在亲密关系里最需要调整的地方是什么？' },
  { category: '婚恋', question: '我感情不顺更容易出在选择对象还是相处方式？' },
  { category: '婚恋', question: '如果进入长期关系，我最需要注意什么问题？' },
  { category: '婚恋', question: '我在感情里更容易付出过多还是防备过重？' },
  { category: '婚恋', question: '我更适合慢热稳定型关系，还是强吸引型关系？' },
  { category: '婚恋', question: '我在关系中最容易触发的矛盾点是什么？' },
  { category: '婚恋', question: '我该怎么判断一段关系值不值得继续投入？' },
  { category: '婚恋', question: '我的婚恋重点更在遇到合适的人，还是学会正确相处？' },
  { category: '子女', question: '我的子女缘分深不深？' },
  { category: '子女', question: '我未来更可能有几个孩子，性别倾向分别是什么？' },
  { category: '子女', question: '我的孩子大概会是什么性格，我适合怎样教育和陪伴？' },
  { category: '子女', question: '关于子女数量和性别，哪些判断缺少可靠依据、需要保守看待？' },
  { category: '子女', question: '我在亲子关系里更适合温和引导还是严格管理？' },
  { category: '子女', question: '我未来与子女的互动重点会体现在哪些方面？' },
  { category: '子女', question: '在子女教育上，我最需要避免什么做法？' },
  { category: '子女', question: '我与子女的关系更容易亲近还是有距离感？' },
  { category: '子女', question: '我在对子女的期待上会不会给自己太大压力？' },
  { category: '子女', question: '面对子女问题，我更该重视沟通还是规则建立？' },
  { category: '子女', question: '我的亲子关系中最需要注意的情绪模式是什么？' },
  { category: '六亲', question: '我和父母之间的关系重点与压力点是什么？' },
  {
    category: '六亲',
    question: '我六亲家人的健康整体怎么样，哪些亲人更需要多关注？',
  },
  {
    category: '六亲',
    question: '父母、兄弟姐妹、伴侣和子女各自更需要注意哪些健康或照护问题？',
  },
  {
    category: '六亲',
    question: '面对家人健康和照护压力，我现在最该提前做哪些安排？',
  },
  { category: '六亲', question: '我和兄弟姐妹之间更容易互助还是有隐性消耗？' },
  { category: '六亲', question: '我在家庭关系中更容易承担责任，还是容易被关系拖累？' },
  { category: '六亲', question: '面对家人问题，我更适合主动介入还是保持边界？' },
  { category: '六亲', question: '我在家庭里更像支持者、协调者，还是承压者？' },
  { category: '六亲', question: '我与家人之间最需要厘清的边界问题是什么？' },
  { category: '六亲', question: '我在家庭责任分配上是否容易失衡？' },
  { category: '六亲', question: '我和原生家庭的影响更偏助力还是牵制？' },
  { category: '六亲', question: '我应该怎样处理亲情中的愧疚感和责任感？' },
  { category: '家庭', question: '我现在最需要调整的家庭边界问题是什么？' },
  { category: '家庭', question: '我的安全感更多要靠家庭关系，还是靠自己建立秩序？' },
  { category: '家庭', question: '我当前的家庭压力主要来自责任、情绪还是现实安排？' },
  { category: '家庭', question: '我更适合怎样经营居住环境，才能让状态更稳定？' },
  {
    category: '家庭',
    question: '我现在适合搬家、换城市或调整居住安排吗？',
  },
  {
    category: '家庭',
    question: '如果考虑买房或长期定居，现在是合适的时机吗？',
  },
  {
    category: '家庭',
    question: '这次居住调整更像机会，还是会带来额外压力和消耗？',
  },
  {
    category: '家庭',
    question: '我现在更适合长期留在当前城市，还是考虑换城市重新扎根发展？',
  },
  {
    category: '家庭',
    question: '如果我要考虑长期定居，这一步更像顺势落地，还是还需要再观察一段时间？',
  },
  {
    category: '家庭',
    question: '这次换城或定居调整，真正要优先看的，是事业机会、生活稳定还是家庭牵动？',
  },
  { category: '家庭', question: '面对家里的长期议题，我现在更该协调、扛住，还是先立边界？' },
  { category: '家庭', question: '我和家人之间最需要先修复的是沟通、距离感还是责任分工？' },
  { category: '人际', question: '我在人际关系里最容易被误解的地方是什么？' },
  { category: '人际', question: '我当前最该筛掉哪类消耗型关系？' },
  { category: '人际', question: '我更适合主动经营人脉，还是把重心放在稳定合作关系上？' },
  { category: '人际', question: '我在合作中最容易吃亏的点是表达、边界还是利益分配？' },
  { category: '人际', question: '我现在的人际阻力主要来自外部环境，还是自己的互动方式？' },
  { category: '人际', question: '我更容易吸引到帮助我的贵人，还是让自己分心的关系？' },
  { category: '情绪', question: '我当前最容易被什么事情触发情绪波动？' },
  { category: '情绪', question: '我现在的内耗更像压力累积，还是安全感不足？' },
  { category: '情绪', question: '当我状态不稳时，最该先调整的是节奏、边界还是表达方式？' },
  { category: '情绪', question: '我是不是容易把关系问题、工作压力或家庭责任压在心里？' },
  { category: '情绪', question: '我最需要建立的情绪修复方式是什么？' },
  { category: '情绪', question: '我现在最该先处理哪种情绪模式，才能让状态稳下来？' },
  { category: '健康', question: '我的身体最需要注意哪些方面？' },
  { category: '健康', question: '我当前更容易出现情绪压力，还是身体透支问题？' },
  { category: '健康', question: '我的作息、饮食、运动里最该先调整哪一项？' },
  { category: '健康', question: '我在健康管理上最容易忽视的隐患是什么？' },
  { category: '健康', question: '我更需要注意慢性消耗，还是突然性的身体失衡？' },
  { category: '健康', question: '我的健康问题更容易和情绪、压力有关吗？' },
  { category: '健康', question: '如果只调整一个生活习惯，最该先改什么？' },
  { category: '健康', question: '我在休息和恢复方面最容易出现什么问题？' },
  { category: '学业', question: '我现在更适合稳扎稳打复习，还是集中突破短板？' },
  { category: '学业', question: '我的学习效率更依赖方法、节奏，还是环境管理？' },
  { category: '学业', question: '我在考试或面试场景里最容易出问题的环节是什么？' },
  {
    category: '学业',
    question: '我现在适合考证、读研进修，还是先把现实节奏稳住？',
  },
  {
    category: '学业',
    question: '如果继续深造，我更适合短期考证、长期进修，还是跨领域学习？',
  },
  {
    category: '学业',
    question: '这次学习投入对我来说更像值得冲刺的机会，还是成本过高的消耗？',
  },
  {
    category: '学业',
    question: '这次考试、面试或申请，我现在更适合全力冲刺、稳住发挥，还是先调整预期？',
  },
  {
    category: '学业',
    question: '如果我想争取这次上岸机会，现在最大的关键在准备节奏、临场发挥还是目标选择？',
  },
  {
    category: '学业',
    question: '这次考试或申请更像值得硬冲的窗口，还是该先稳住节奏避免失误？',
  },
  { category: '学业', question: '如果继续进修，我更适合偏理论、偏实践，还是跨领域学习？' },
  { category: '学业', question: '我当前学业上的主要卡点更在专注力、理解力还是执行力？' },
  { category: '学业', question: '我现在最该先补哪一种学习能力，才能更快看到提升？' },
  { category: '成长', question: '我现在最需要先突破的性格卡点是什么？' },
  { category: '成长', question: '我反复卡住的旧模式，更多出现在关系、事业还是情绪里？' },
  { category: '成长', question: '我当前的人生课题更偏向学会坚持，还是学会放下？' },
  { category: '成长', question: '如果想让自己真正往前走，我最该先改哪一个习惯或观念？' },
  { category: '成长', question: '我现在更适合主动变动，还是先把内部状态整稳？' },
  { category: '成长', question: '我最需要整合的矛盾，是想要安全感还是想要更大空间？' },
  { category: '天赋', question: '我最值得长期放大的核心优势是什么？' },
  { category: '天赋', question: '我的表达、创造或组织能力更适合在哪类场景里发挥？' },
  { category: '天赋', question: '我最容易被别人看见和认可的能力是什么？' },
  { category: '天赋', question: '我的优势更适合做专业深耕、内容表达，还是资源整合？' },
  { category: '天赋', question: '我有哪些天赋其实已经有了，只是还没有用对地方？' },
  { category: '天赋', question: '如果只挑一个最该重点投资的能力方向，会是哪一个？' },
];

export const baziSingleShortcutActions = [
  { label: '综合' as const, promptId: 'ai-mingge-zonglun' },
  { label: '近期' as const, promptId: 'ai-recent' },
  { label: '事业' as const, promptId: 'ai-career' },
  { label: '换工作' as const, promptId: 'ai-job-change' },
  { label: '创业合作' as const, promptId: 'ai-startup-partnership' },
  { label: '投资合作' as const, promptId: 'ai-investment-partnership' },
  { label: '财运' as const, promptId: 'ai-wealth-timing' },
  { label: '婚恋' as const, promptId: 'ai-marriage' },
  { label: '关系推进' as const, promptId: 'ai-relationship-push' },
  { label: '关系去留' as const, promptId: 'ai-relationship-decision' },
  { label: '复合判断' as const, promptId: 'ai-reconciliation-decision' },
  { label: '子女' as const, promptId: 'ai-children-fate' },
  { label: '六亲' as const, promptId: 'ai-family' },
  { label: '家庭' as const, promptId: 'ai-home' },
  { label: '搬家置业' as const, promptId: 'ai-home-move' },
  { label: '定居换城' as const, promptId: 'ai-settle-relocate' },
  { label: '人际' as const, promptId: 'ai-social' },
  { label: '情绪' as const, promptId: 'ai-emotion' },
  { label: '健康' as const, promptId: 'ai-health' },
  { label: '学业' as const, promptId: 'ai-study' },
  { label: '考证进修' as const, promptId: 'ai-study-advance' },
  { label: '考试上岸' as const, promptId: 'ai-exam-landing' },
  { label: '成长' as const, promptId: 'ai-growth' },
  { label: '天赋' as const, promptId: 'ai-talent' },
] as const;

export const baziCompatibilityShortcutActions = [
  { label: '合婚' as const, promptId: 'ai-compat-marriage' },
  { label: '合伙' as const, promptId: 'ai-compat-career' },
  { label: '友情' as const, promptId: 'ai-compat-friendship' },
  { label: '子女' as const, promptId: 'ai-compat-children' },
  { label: '父母' as const, promptId: 'ai-compat-parents' },
  { label: '兄弟' as const, promptId: 'ai-compat-siblings' },
] as const;

export const ziweiSingleShortcutActions = [
  { label: '综合' as const, topic: 'life' },
  { label: '近期' as const, topic: 'recent' },
  { label: '事业' as const, topic: 'career-wealth' },
  { label: '换工作' as const, topic: 'job-change' },
  { label: '创业合作' as const, topic: 'startup-partnership' },
  { label: '投资合作' as const, topic: 'investment-partnership' },
  { label: '财运' as const, topic: 'career-wealth' },
  { label: '婚恋' as const, topic: 'relationship' },
  { label: '关系推进' as const, topic: 'relationship-push' },
  { label: '关系去留' as const, topic: 'relationship-decision' },
  { label: '复合判断' as const, topic: 'reconciliation-decision' },
  { label: '子女' as const, topic: 'children' },
  { label: '六亲' as const, topic: 'family' },
  { label: '家庭' as const, topic: 'family' },
  { label: '搬家置业' as const, topic: 'home-move' },
  { label: '定居换城' as const, topic: 'settle-relocate' },
  { label: '人际' as const, topic: 'social' },
  { label: '情绪' as const, topic: 'emotion' },
  { label: '健康' as const, topic: 'health' },
  { label: '学业' as const, topic: 'study' },
  { label: '考证进修' as const, topic: 'study-advance' },
  { label: '考试上岸' as const, topic: 'exam-landing' },
  { label: '成长' as const, topic: 'growth' },
  { label: '天赋' as const, topic: 'talent' },
] as const;

export const ziweiCompatibilityShortcutActions = [
  { label: '感情' as const, topic: 'relationship' },
  { label: '合作' as const, topic: 'career-wealth' },
  { label: '相处' as const, topic: 'chat' },
] as const;

export const ziweiScopeLabelMap: Record<ZiweiScopeMode, string> = {
  origin: '本命',
  full: '完整输出',
  decadal: '大限',
  yearly: '流年',
  monthly: '流月',
  daily: '流日',
  hourly: '流时',
};

export const singlePromptShortcutSections = [
  {
    key: 'overview',
    title: '通用',
    description: '分析整体命盘与近期趋势。',
    labels: ['综合', '近期'],
  },
  {
    key: 'career',
    title: '工作财务',
    description: '只选择分析范围，不预置固定问法。',
    labels: ['事业', '换工作', '创业合作', '投资合作', '财运'],
  },
  {
    key: 'relationship',
    title: '关系家庭',
    description: '只选择分析范围，具体问题可留空或自填。',
    labels: ['婚恋', '关系推进', '关系去留', '复合判断', '子女', '六亲', '家庭'],
  },
  {
    key: 'life',
    title: '生活成长',
    description: '只选择分析范围，不使用本地固定问题。',
    labels: [
      '搬家置业',
      '定居换城',
      '人际',
      '情绪',
      '健康',
      '学业',
      '考证进修',
      '考试上岸',
      '成长',
      '天赋',
    ],
  },
] as const;

export const ZIWEI_GRID_ORDER = [
  3,
  4,
  5,
  6,
  2,
  'center',
  'center-skip',
  7,
  1,
  'center-skip',
  'center-skip',
  8,
  0,
  11,
  10,
  9,
] as const;
export const PROMPT_DRAFT_STORAGE_PREFIX = 'result-prompt-draft';
